### ISSUE TITLE
Esse exit aqui tá uma porra

### ISSUE THREAD

**Issue by lucasrigato** [rhuangabrielsantos/Formula1-Project#15]
https://github.com/rhuangabrielsantos/F1-Project/blob/ff69f2cebffbe8829fda622b621c0f72770eda65/app/Controllers/CarController.php#L52

**Comment by rhuangabrielsantos** [comment]
Ai seu filha da mãe, tomei vergonha na cara e resolvi esses exit 
#16 
@lucasrigato
